name: Standalone-Dispatch-By-User

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Branch/ref for the standalone'
        required: true
        default: 'develop'
      base:
        description: 'Base number'
        required: true
        default: 'base number, e.g. latest or 35'
      version:
        description: 'Version to be build, take from tag ORA-<version>'
        required: true
        default: 'version, e.g. 5.1.0'

jobs:
  docker:
    if: ${{ github.repository == 'OpenRoberta/openroberta-lab' }}
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout the branch
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.inputs.branch }}
      - name: Set up QEMU for multi architecture build
        uses: docker/setup-qemu-action@master
        with:
          platforms: linux/amd64
      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build docker image for standalone
        uses: docker/build-push-action@v3
        with:
          builder: ${{ steps.buildx.outputs.name }}
          context: .
          file: ./Resources/dockerStandalone/Dockerfile
          build-args: BASEVERSION=${{ github.event.inputs.base }}
          platforms: linux/amd64
          push: true
          tags: openroberta/standalone:latest, openroberta/standalone:${{ github.event.inputs.version }}

