name: IntegrationTest-Scheduled-By-Cron

on:
  schedule:
    - cron: "30 0 * * *"

jobs:
  integration-test:
    if: ${{ github.repository == 'OpenRoberta/openroberta-lab' }}
    runs-on: ubuntu-22.04
    container: openroberta/base-x64:latest
    steps:
      - name: branch ${{ github.ref }}, repo ${{ github.repository }}, ora-cc-rsc-tag is latest
        uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'adopt'
      - name: Cache local maven repository
        uses: actions/cache@v3
        with:
          path: /root/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
      - name: Build with maven and run integration tests
        run: mvn --batch-mode clean install -PrunIT
